version: '3.7'

services:
  web:
    build:
      target: dev
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
    volumes:
      - './:/var/www/html/'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - 9191:80

  php_cli:
    build:
      context: .
      dockerfile: Cli.DockerFile
      args:
        PHP_VERSION: 7.1.29
    tty: true