version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Web.DockerFile
    ports:
      - '8002:80'
#      todo: find a way to volume not override the already existing content
    volumes:
      - './:/var/www/html/'